// Team member data for Maths N Tech Club (MNTC)

export interface TeamMember {
  id: number;
  name: string;
  avatar: string;
  position: string;
  facebook?: string;
  instagram?: string;
  linkedin?: string;
  github?: string;
}

export interface TeamCategory {
  categoryName: string;
  members: TeamMember[];
}

export const teamData: Record<string, TeamCategory> = {
  faculty: {
    categoryName: "Faculty Advisors",
    members: [
      {
        id: 1,
        name: "Dr. Lakshmi Kanta Dey",
        avatar: "/images/member images/year 0/lakshmi.jpg",
        position: "Associate Professor",
      },
      {
        id: 2,
        name: "Dr. Pinaki Pal",
        avatar: "/images/member images/year 0/pinaki.jpg",
        position: "Associate Professor",
      },
    ]
  },
  secondYear: {
    categoryName: "Second Year",
    members: [
      {
        id: 1,
        name: "Aayush Rinwa",
        avatar: "/images/member images/year 1/aayush.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/mr_aayush_offical_?igsh=MTB6b3R4NnRjaTZyNg==",
        linkedin: "https://www.linkedin.com/in/aayush-rinwa-a46b5832b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 2,
        name: "Mohammed Ayaan Ahmed",
        avatar: "/images/member images/year 1/ayaan.jpg",
        position: "Web Developer",
        instagram: "https://www.instagram.com/moh_ayaan_33?igsh=bWJhdHpmZ3AxM3Rn",
        linkedin: "https://www.linkedin.com/in/mohammed-ayaan-ahmed-908077365?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 3,
        name: "Nivesh Gupta",
        avatar: "/images/member images/year 1/nivesh.jpg",
        position: "Graphic designer",
        instagram: "https://www.instagram.com/nivesh_.4?utm_source=qr&igsh=MTc0ajVyZG16cHB6cg==",
        linkedin: "https://www.linkedin.com/in/nivesh-gupta-646119323?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 4,
        name: "Komal Ram Chodapaneedi",
        avatar: "/images/member images/year 1/komal.jpg",
        position: "Graphic Designer",
        instagram: "18_____komal",
        linkedin: "https://www.linkedin.com/in/komalram-chodapaneedi-560b84346?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 5,
        name: "Ipshita Mandal",
        avatar: "/images/member images/year 1/ipshita.jpg",
        position: "Web developer",
        instagram: "https://www.instagram.com/ipsh.ita___/",
        linkedin: "https://www.linkedin.com/in/ipshita-mandal-680729317?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 6,
        name: "TRIJAYEE BARUA",
        avatar: "/images/member images/year 1/trijayee.jpg",
        position: "Graphic Designer",
        instagram: "https://www.instagram.com/_trizzzz.__?igsh=MXFpd2EyNGwzNWVyYg==",
        linkedin: "https://www.linkedin.com/in/trijayee-barua-56182a359?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 7,
        name: "Pranav Tokasia",
        avatar: "/images/member images/year 1/pranav.jpg",
        position: "Content Writing",
        instagram: "https://www.instagram.com/tokasiapranav?igsh=MWx3N3YxMzNnY3Y2aA==",
        linkedin: "https://www.linkedin.com/in/pranav-tokasia-6a028a324?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 8,
        name: "RIDDHI GAUTAM",
        avatar: "/images/member images/year 1/riddhi.jpg",
        position: "Graphic Designer",
        instagram: "https://www.instagram.com/_riddhi_gautam?igsh=MTRrdjdyMDJ0b253dg==",
        linkedin: "https://www.linkedin.com/in/riddhi-gautam-bba997316?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 9,
        name: "Samium Umaira",
        avatar: "/images/member images/year 1/samium.jpg",
        position: "Content Writing",
        instagram: "https://www.instagram.com/tokasiapranav?igsh=MWx3N3YxMzNnY3Y2aA==",
        linkedin: "https://www.linkedin.com/in/samium-umaira-504569279?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 10,
        name: "Debolina Bose",
        avatar: "/images/member images/year 1/debolina.jpg",
        position: "Content Writing",
        instagram: "https://www.instagram.com/its_debo_05?utm_source=qr&igsh=eDJtdzhjcXpjYTU2",
        linkedin: "https://www.linkedin.com/in/debolina-bose-420a24324?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 11,
        name: "Tannu Rao",
        avatar: "/images/member images/year 1/tannu.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/__tannurao___?igsh=YzljYTk1ODg3Zg==",
        linkedin: "https://www.linkedin.com/in/tannu-rao-44718b326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 12,
        name: "Arepally Sai Krishna",
        avatar: "/images/member images/year 1/krishna.jpg",
        position: "Web developer",
        instagram: "https://www.instagram.com/sai_krishna_.2?igsh=MmpjcWo3NXlvazNo",
        linkedin: "https://www.linkedin.com/in/sai-krishna-368328324?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 13,
        name: "Arpita Dash",
        avatar: "/images/member images/year 1/arpita.jpg",
        position: "Graphic Designiner",
      },
      {
        id: 14,
        name: "Aman Brahma",
        avatar: "/images/aman.jpg",
        position: "Web Developer",
        instagram:"https://www.instagram.com/aman.brahma/?hl=en",
        linkedin:"https://www.linkedin.com/in/aman-brahma-141282315/"
      }
    ]
  },
  thirdYear: {
    categoryName: "Third Year",
    members: [
      {
        id: 1,
        name: "Rudransh Tripathi",
        avatar: "/images/member images/year 2/rudransh.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/_rudranshtripathi_/",
        linkedin: "https://www.linkedin.com/in/rudransh-tripathi-9179182b3/",
      },
      {
        id: 2,
        name: "Debargha Ghosh",
        avatar: "/images/member images/year 2/debargha.jpg",
        position: "Content Writer",
        instagram: "https://www.instagram.com/vandox8132?igsh=MTdsYzU1Yjh1OGtsYw==",
        linkedin: "https://www.linkedin.com/in/debargha-ghosh-ba7555282",
      },
      {
        id: 3,
        name: "Aditya Pratap singh",
        avatar: "/images/member images/year 2/aditya.jpg",
        position: "Web developer",
        instagram: "https://www.instagram.com/adi_tya_pra_tap/?next=%2F",
        linkedin: "https://www.linkedin.com/in/aditya-pratap-singh-79646b282/",
      },
      {
        id: 4,
        name: "Vishesh Patel",
        avatar: "/images/member images/year 2/vishesh.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/visheshpatel_26?igsh=NmR6MWM4dmU4N2t3&utm_source=qr",
        linkedin: "https://www.linkedin.com/in/vishesh-patel-06861529a",
      },
      {
        id: 5,
        name: "Shaswat Ranjan",
        avatar: "/images/member images/year 2/shaswat.jpg",
        position: "Graphic Designers",
      },
      {
        id: 6,
        name: "Anirudra Kisku",
        avatar: "/images/member images/year 2/anirudra.jpg",
        position: "Graphic Designers",
        instagram: "https://www.instagram.com/anirudra_kisku?igsh=MXAyM29naDMxNTVjdQ==",
        linkedin: "https://www.linkedin.com/in/anirudra-kisku-4335821b5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 7,
        name: "Sakshi Kumari Roy",
        avatar: "/images/member images/year 2/sakshi.jpg",
        position: "Graphic Designers",
        instagram: "https://www.instagram.com/saksh.iroy05?igsh=MTMxMHduY3dzNTd0YQ==",
        linkedin: "https://www.linkedin.com/in/sakshi-roy-bb29762b3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 8,
        name: "Krish Kumar J",
        avatar: "/images/member images/year 2/krish.jpg",
        position: "Video Editors",
        instagram: "https://www.instagram.com/kr1shj?igsh=MWRybDg5cTJuMDE2aA==",
        linkedin: "https://in.linkedin.com/in/krish-kumar-54bb52293",
      },
      {
        id: 9,
        name: "Kaushal Kumar",
        avatar: "/images/member images/year 2/kaushal.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/kaushal878k._?igsh=N2poZHU0cDJya2Vr&utm_source=qr",
        linkedin: "https://www.linkedin.com/in/kaushal-kumar-990375286?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
      },
      {
        id: 10,
        name: "Mukesh Saran",
        avatar: "/images/member images/year 2/mukesh.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/invites/contact/?igsh=tno0l74by79m&utm_content=lsu725j",
        linkedin: "https://www.linkedin.com/in/mukesh-saran-7a0225291?fbclid=PAZXh0bgNhZW0CMTEAAaa8jtxo9AOFGAC5vHhiWxm8uSrj-yrellhBYatrtjwlYoDjD2Ct8R7FuCQ_aem_XW-7lAaScVdIX_FzSK2mlQ",
      },
      {
        id: 11,
        name: "Sumit Kumar",
        avatar: "/images/member images/year 2/sumit.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/sumit565963?utm_source=qr&igsh=cnZmNGkxNmJpbDh5",
        linkedin: "https://www.linkedin.com/in/sumit-kumar-00083229a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 12,
        name: "Suryansh Mishra",
        avatar: "/images/member images/year 2/suryansh.jpg",
        position: "Graphic Designers",
        instagram: "https://www.instagram.com/m_suryansh_?igsh=cnB6eTl6bDFqOTBw",
        linkedin: "https://www.linkedin.com/in/suryansh-mishra-9b7816290?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 13,
        name: "Jit Sarkar",
        avatar: "/images/member images/year 2/jit.jpg",
        position: "Web Developer",
        instagram: "https://www.instagram.com/__jee_t/?hl=en",
        linkedin: "https://www.linkedin.com/in/jit-sarkar-b26875292/",
      },
      {
        id: 14,
        name: "Narayan Hansdah",
        avatar: "/images/member images/year 2/narayan.jpg",
        position: "Graphic Designers",
        instagram: "https://www.instagram.com/_hansdah_babu_/",
        linkedin: "https://www.linkedin.com/in/narayan-hansdah-35b3aa2b4/",
      },
      {
        id: 15,
        name: "Shivam Kumar",
        avatar: "/images/member images/year 2/shivam.jpg",
        position: "Web Developer",
        instagram: "https://www.instagram.com/shivamkumar0.88?igsh=MWZ1cTBtZmRhdXR0Ng==",
        linkedin: "https://www.linkedin.com/in/shivam-kumar-8b6452285?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 16,
        name: "Saraswat Sahoo",
        avatar: "/images/member images/year 2/saraswat.jpg",
        position: "Web Developer",
        instagram: "https://www.instagram.com/sahoo.saraswat/profilecard/?igsh=MXN5Y25wbm84ZWNnbw==",
        linkedin: "https://www.linkedin.com/in/saraswat-sahoo-5ab364288?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 17,
        name: "Kajal Kumari",
        avatar: "/images/member images/year 2/kajal.jpg",
        position: "Event & Ideation",
        instagram: "https://www.instagram.com/k_kajal06?igsh=MWNpb3Mxc2t0Y3Nvbg%3D%3D&utm_source=qr",
        linkedin: "https://www.linkedin.com/in/kajal-kumari-b389832a4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
      },
      {
        id: 18,
        name: "Utsav Biswas",
        avatar: "/images/member images/year 2/utsav.jpg",
        position: "Video Editor",
        instagram: "https://www.instagram.com/curious_utsav3?utm_source=qr&igsh=dGJnd3dxNzExdDY4",
      },
      {
        id: 19,
        name: "Dibyendu Guru",
        avatar: "/images/member images/year 2/dibyendu.jpg",
        position: "Event & Ideation",
        instagram: "http://instagram.com/dibyenduguru/",
        linkedin: "http://linkedin.com/in/dibyendu-guru-nitdgp",
      },
    ]
  },
  fourthYear: {
    categoryName: "Fourth Year",
    members: [
      {
        id: 1,
        name: "Shreyansh Agrahari",
        avatar: "/images/member images/year 3/shreyansh.jpg",
        position: "President",
        facebook: "https://www.facebook.com/profile.php?id=100089255712027",
        instagram: "https://instagram.com/shreyansh_agrahari_16?igshid=NGExMmI2YTkyZg==",
        linkedin: "https://www.linkedin.com/in/shreyansh-agrahari-73085224b",
      },
      {
        id: 2,
        name: "Soham Bhattacharya",
        avatar: "/images/member images/year 3/soham2.jpeg",
        position: "General Secretary",
        facebook: "https://www.facebook.com/iamSohamB",
        instagram: "https://instagram.com/iamsohamb?igshid=NGExMmI2YTkyZg==",
        linkedin: "https://www.linkedin.com/in/soham-bhattacharya-75b858269",
      },
      {
        id: 3,
        name: "Ranit Barua",
        avatar: "/images/member images/year 3/ranit.jpg",
        position: "Treasurer",
        facebook: "https://www.facebook.com/profile.php?id=100092757409184&mibextid=ZbWKwL",
        instagram: "https://instagram.com/ranitbarua2004?igshid=MzRlODBiNWFlZA==",
        linkedin: "https://www.linkedin.com/in/ranit-barua-a46a93256",
      },
      {
        id: 4,
        name: "Koushik Kumar Paul",
        avatar: "/images/member images/year 3/koushik.jpg",
        position: "Vice President",
        facebook: "https://www.facebook.com/profile.php?id=100084201651469&mibextid=ZbWKwL",
        instagram: "https://instagram.com/kou_s_hik_14?igshid=MzNlNGNkZWQ4Mg==",
        linkedin: "https://www.linkedin.com/in/koushik-kumar-paul-b62915264",
      },
      {
        id: 5,
        name: "Shivam Singh",
        avatar: "/images/member images/year 3/shivam.jpg",
        position: "Associate General Secretary",
        facebook: "https://www.facebook.com/profile.php?id=100090016507218&mibextid=ZbWKwL",
        instagram: "https://www.instagram.com/shivam.singh_ss/",
        linkedin: "https://www.linkedin.com/in/shivam-singh-050417264",
      },
      {
        id: 6,
        name: "Prashant Moryani",
        avatar: "/images/member images/year 3/prashant.jpg",
        position: "Convener",
        facebook: "https://www.facebook.com/profile.php?id=100092750539614",
        instagram: "https://instagram.com/prashant.moryani?igshid=OGQ5ZDc2ODk2ZA==",
        linkedin: "https://www.linkedin.com/in/prashant-moryani-3b2384252",
      },
      {
        id: 7,
        name: "Poulami Karmakar",
        avatar: "/images/member images/year 3/poulami.jpg",
        position: "Head of Corporate & Communication",
        facebook: "https://www.facebook.com/profile.php?id=100089202477863&mibextid=ZbWKwL",
        instagram: "https://instagram.com/pur_epsyche?igshid=MzNlNGNkZWQ4Mg==",
        linkedin: "https://www.linkedin.com/in/poulami-karmakar-a66185278",
      },
      {
        id: 8,
        name: "Sayan Banerjee",
        avatar: "/images/member images/year 3/sayan.jpg",
        position: "Tech Head",
        facebook: "https://www.facebook.com/profile.php?id=100027520621727",
        instagram: "https://www.instagram.com/sayan_banerjee____/",
        linkedin: "https://www.linkedin.com/in/sayan-banerjee-77603a23b/",
      },
      {
        id: 9,
        name: "Aditya Pratap Ram",
        avatar: "/images/member images/year 3/aditya.jpg",
        position: "Co-Treasurer",
        facebook: "https://www.facebook.com/profile.php?id=100025406300434&mibextid=ZbWKwL",
        instagram: "https://instagram.com/why_is_aditya?igshid=MzNlNGNkZWQ4Mg==",
        linkedin: "https://www.linkedin.com/in/aditya-ram-248b8b277",
      },
      {
        id: 10,
        name: "Vishal Raghav",
        avatar: "/images/member images/year 3/vishal.jpg",
        position: "PR Head",
        facebook: "https://www.facebook.com/bijay.raghav.16?mibextid=ZbWKwL",
        instagram: "https://instagram.com/_vishal_raghav535?igshid=MzNlNGNkZWQ4Mg==",
        linkedin: "https://www.linkedin.com/in/vishal-raghav-a15610261",
      },
      {
        id: 11,
        name: "Vaibhav Kumar Trave",
        avatar: "/images/member images/year 3/vaibhav.jpg",
        position: "PR Head",
        facebook: "https://www.facebook.com/profile.php?id=100092552908006",
        instagram: "https://instagram.com/vaibhavtarve?igshid=MzNlNGNkZWQ4Mg==",
        linkedin: "https://www.linkedin.com/in/vaibhav-t-27a360252",
      },
      {
        id: 12,
        name: "Sneha Singh",
        avatar: "/images/member images/year 3/sneha.jpg",
        position: "Design Head",
        facebook: "https://www.facebook.com/profile.php?id=100092562927331&mibextid=ZbWKwL",
        instagram: "https://instagram.com/__sneha_singh19?igshid=MzNlNGNkZWQ4Mg==",
        linkedin: "https://www.linkedin.com/in/sneha-singh-71aa5a268",
      },
      {
        id: 13,
        name: "Aditi Mahato",
        avatar: "/images/member images/year 3/aditi.jpg",
        position: "Event & ATH Head",
        facebook: "https://www.facebook.com/profile.php?id=100093171608393",
        instagram: "https://www.instagram.com/___._aditi_.___/",
        linkedin: "https://www.linkedin.com/in/aditi-mahto-581bb3278",
      },
      {
        id: 14,
        name: "Soumen Sen",
        avatar: "/images/member images/year 3/soumen.jpg",
        position: "Finance Head",
        facebook: "https://www.facebook.com/profile.php?id=100092653397516",
        instagram: "https://instagram.com/_soumenmegh?igshid=MzNlNGNkZWQ4Mg==",
        linkedin: "https://www.linkedin.com/in/soumen-sen-7b6100250",
      },
    ]
  },
  alumni_2020_24: {
    categoryName: "Alumni 2020-24",
    members: [
      {
        id: 1,
        name: "Kabita",
        avatar: "/images/member images/year 5/kabita.jpg",
        position: "PRESIDENT",
        facebook: "https://www.facebook.com/kabita.harijan.96",
        instagram: "https://www.instagram.com/kabita_harijan/",
        linkedin: "https://www.linkedin.com/in/kabita-harijan-33a4b0202/",
      },
      {
        id: 2,
        name: "Debjit",
        avatar: "/images/member images/year 5/debjit.jpeg",
        position: "GENERAL SECRETARY",
        facebook: "https://m.facebook.com/profile.php?id=100026349304600",
        instagram: "https://www.instagram.com/deb_jit_03_/",
        linkedin: "https://www.linkedin.com/in/debjit-maji-51a623202",
      },
      {
        id: 3,
        name: "Devansh",
        avatar: "/images/member images/year 5/devansh.jpeg",
        position: "VICE PRESIDENT",
        facebook: "https://www.facebook.com/DevanshsinghpatelDSP",
        instagram: "https://instagram.com/albatraozz_8",
        linkedin: "https://www.linkedin.com/in/devansh-patel-147585174",
      },
      {
        id: 4,
        name: "Swarnali",
        avatar: "/images/member images/year 5/swarnali.jpeg",
        position: "CONVENOR",
        facebook: "https://www.facebook.com/swarnali.saha.1088",
        instagram: "https://instagram.com/swarnaliiii_",
        linkedin: "https://www.linkedin.com/in/swarnali-saha-499a6420a",
      },
      {
        id: 5,
        name: "Rishikesh",
        avatar: "/images/member images/year 5/rishikesh.jpg",
        position: "TREASURER",
        facebook: "https://www.facebook.com/profile.php?id=100011501890597",
        instagram: "http://instagram.com/rkt2600i",
        linkedin: "https://www.linkedin.com/in/rishikesh-tiwari-23848220a",
      },
      {
        id: 6,
        name: "Anurag",
        avatar: "/images/member images/year 5/anurag.jpg",
        position: "TECH HEAD",
        instagram: "https://www.instagram.com/a2_n_u_r_a_g/",
        linkedin: "www.linkedin.com/in/anurag-2-sarkar",
        github: "https://github.com/a2nurag",
      },
      {
        id: 7,
        name: "Jay",
        avatar: "/images/member images/year 5/jay.jpeg",
        position: "RnD HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100015113418530",
        instagram: "https://www.instagram.com/im_mr.jay_015/",
        linkedin: "https://www.linkedin.com/in/jay-gupta-0697321a5",
      },
      {
        id: 8,
        name: "Prannoy",
        avatar: "/images/member images/year 5/prannoy.jpeg",
        position: "SPONSORSHIP HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100060137213715",
        instagram: "https://www.instagram.com/prandom10/",
        linkedin: "https://www.linkedin.com/in/prannoy-chakraborty-ab747b20a/",
      },
      {
        id: 9,
        name: "Ayushi",
        avatar: "/images/member images/year 5/ayushi.jpeg",
        position: "SPONSORSHIP HEAD",
        facebook: "https://www.facebook.com/ayushi.meena.50702",
        instagram: "https://www.instagram.com/ayushiii._.12/",
        linkedin: "https://www.linkedin.com/in/ayushi-meena-404739209",
      },
      {
        id: 10,
        name: "Anubhav",
        avatar: "/images/member images/year 5/anubhav.jpg",
        position: "PR AND FINANCE HEAD",
        linkedin: "https://www.linkedin.com/in/anubhav-mandal-2b9908232/",
      },
      {
        id: 11,
        name: "Prativa",
        avatar: "/images/member images/year 5/prativa.jpg",
        position: "CREATIVE HEAD",
        facebook: "https://www.facebook.com/prativa.sahu.758399",
        instagram: "https://www.instagram.com/im_prajakta_7/",
        linkedin: "https://www.linkedin.com/in/prativa-sahu-900072210",
      },
      {
        id: 12,
        name: "Suraj",
        avatar: "/images/member images/year 5/suraj.jpeg",
        position: "EVENT AND ATH Head",
        facebook: "https://www.facebook.com/profile.php?id=100007805447382",
        instagram: "https://instagram.com/s_rajproo/",
      },
      {
        id: 13,
        name: "Shobhit",
        avatar: "/images/member images/year 5/shobhit.jpg",
        position: "GRAPHICS HEAD",
        facebook: "https://www.facebook.com/shobhit.katiyar.167189",
        instagram: "https://www.instagram.com/kati_yar_shobhit/",
        linkedin: "https://www.linkedin.com/in/shobhit-katiyar-2885a2204",
      },
      {
        id: 14,
        name: "Rupam",
        avatar: "/images/member images/year 5/rupam.jpeg",
        position: "WORKSHOP HEAD",
        facebook: "https://www.facebook.com/rupam.maity.56884/",
        linkedin: "https://www.linkedin.com/in/rupam-maity-553b381b8",
      },
    ]
  },
  alumni_2021_25: {
    categoryName: "Alumni 2021-25",
    members: [
      {
        id: 1,
        name: "Tathagata Das",
        avatar: "/images/member images/year 4/tathagata.jpeg",
        position: "President",
        instagram: "https://www.instagram.com/tathagata_003/",
        linkedin: "https://www.linkedin.com/in/tathagata-das-a12606211/",
        github: "https://github.com/Tathagata003",
      },
      {
        id: 2,
        name: "Mayank Pratap Singh",
        avatar: "/images/member images/year 4/mayank.jpeg",
        position: "Vice President",
        facebook: "https://www.facebook.com/profile.php?id=100075460306785",
        instagram: "https://www.instagram.com/pratapchauhan1625/",
        linkedin: "https://www.linkedin.com/in/mayank-pratap-singh-032329229/",
      },
      {
        id: 3,
        name: "Rajdeep Saha",
        avatar: "/images/member images/year 4/rajdeep.jpeg",
        position: "Treasurer",
        facebook: "https://www.facebook.com/profile.php?id=100072838294525",
        instagram: "https://instagram.com/instarajdeep?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/in/rajdeep-saha-4b787a232",
      },
      {
        id: 4,
        name: "Shivanshu Katiyar",
        avatar: "/images/member images/year 4/shivanshu.jpeg",
        position: "General Secretary",
        facebook: "https://m.facebook.com/100076228405418/",
        instagram: "https://www.instagram.com/katiyar_pranjul1607/",
        linkedin: "https://www.linkedin.com/in/shivanshu-katiyar-811995228",
        github: "https://github.com/Shivanshu1604",
      },
      {
        id: 5,
        name: "Nandini Naidu",
        avatar: "/images/member images/year 4/nandini.jpeg",
        position: "ASSOCIATE GENERAL SECRETARY",
        facebook: "https://www.facebook.com/profile.php?id=100080201448428",
        instagram: "https://www.instagram.com/invites/contact/?i=103ehlrhupp3z&utm_content=5zvgqvw",
      },
      {
        id: 6,
        name: "Ashmi Chattaraj",
        avatar: "/images/member images/year 4/ashmi.jpeg",
        position: "CONVENER",
        facebook: "https://www.facebook.com/profile.php?id=100075338811226",
        instagram: "https://instagram.com/imcrazyac?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/in/ashmi-chattaraj",
      },
      {
        id: 7,
        name: "Likhitha Reddy",
        avatar: "/images/member images/year 4/likhitha.jpeg",
        position: "TECH HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100077402552501",
        instagram: "https://www.instagram.com/likhi9_",
        linkedin: "https://www.linkedin.com/in/sai-likhitha-reddy-a3659a231",
        github: "https://github.com/likhitha-reddy",
      },
      {
        id: 8,
        name: "Srabani Sahoo",
        avatar: "/images/member images/year 4/srabani.jpeg",
        position: "RnD Head",
        instagram: "https://www.instagram.com/sahoo.srabani/",
        linkedin: "https://www.linkedin.com/mwlite/in/srabani-sahoo-3b7756214",
      },
      {
        id: 9,
        name: "Menaka Sirisha",
        avatar: "/images/member images/year 4/menaka.jpeg",
        position: "Event Manager",
        facebook: "https://www.facebook.com/profile.php?id=100078007337598",
        instagram: "https://www.instagram.com/__sirisha__27/",
        linkedin: "https://www.linkedin.com/in/sirisha-menaka-270a15231",
      },
      {
        id: 10,
        name: "Nisha Parvin",
        avatar: "/images/member images/year 4/nisha.jpeg",
        position: "SPONSORSHIP HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100076665036113",
        linkedin: "https://www.linkedin.com/in/nisha-parvin-4b0515245",
      },
      {
        id: 11,
        name: "Urmi Sharma",
        avatar: "/images/member images/year 4/urmi.jpeg",
        position: "Finance Cell Head",
        facebook: "https://www.facebook.com/profile.php?id=100076386226790",
        instagram: "https://www.instagram.com/urmi._02/",
        linkedin: "https://www.linkedin.com/in/urmi-sharma-030536229",
      },
      {
        id: 12,
        name: "Joychir Hansda",
        avatar: "/images/member images/year 4/joychir.jpeg",
        position: "DESIGN HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100078145237796",
        instagram: "https://instagram.com/punk__production?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/in/joychir-hansda-b22581213",
      },
      {
        id: 13,
        name: "Yash Soni",
        avatar: "/images/member images/year 4/yash_soni.jpeg",
        position: "SPONSORSHIP HEAD",
        facebook: "https://www.facebook.com/yash.baradia.961",
        instagram: "https://www.instagram.com/invites/contact/?i=18v2ld0hosdag&utm_content=3kiuabf",
        linkedin: "https://www.linkedin.com/in/yash-soni-aabab7223",
      },
      {
        id: 14,
        name: "Sabyasachi Satapathy",
        avatar: "/images/member images/year 4/sabya.jpeg",
        position: "VIDEO AND PRODUCTION HEAD",
        facebook: "https://m.facebook.com/100004724385659/",
        instagram: "https://instagram.com/kss706?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/mwlite/in/sabyasachi-satapathy-66914122a",
      },
      {
        id: 15,
        name: "Yash Paswan",
        avatar: "/images/member images/year 4/yash_paswan.jpeg",
        position: "EVENT & RND HEAD",
        facebook: "https://www.facebook.com/yash.paswan.7731",
        instagram: "https://www.instagram.com/utkarsh9652/",
        linkedin: "https://www.linkedin.com/in/utkarsh-kumar-078626201",
      },
      {
        id: 16,
        name: "Tanisha Roy",
        avatar: "/images/member images/year 4/tanisha.jpeg",
        position: "RND HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100076149264976",
        instagram: "https://instagram.com/troy_quotes?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/in/tanisha-roy-881b24231",
      },
      {
        id: 17,
        name: "Riya Maiti",
        avatar: "/images/member images/year 4/riya.jpeg",
        position: "CREATIVE HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100074318982774",
        instagram: "https://www.instagram.com/riya.amaze/",
        linkedin: "https://www.linkedin.com/in/riya-maiti-772b34230",
      },
      {
        id: 18,
        name: "Utkarsh Kumar",
        avatar: "/images/member images/year 4/utkarsh.jpeg",
        position: "WORKSHOP HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100057396392171",
        instagram: "https://www.instagram.com/utkarsh9652/",
        linkedin: "https://www.linkedin.com/in/utkarsh-kumar-078626201",
      },
    ]
  },
  alumni_2019_23: {
    categoryName: "Alumni 2019-23",
    members: [
      {
        id: 1,
        name: "Abantika",
        avatar: "/images/member images/year 6/abantika.jpg",
        position: "PRESIDENT",
        facebook: "https://www.facebook.com/abantika.basu.5",
        instagram: "https://instagram.com/abantika_basu/",
        linkedin: "https://www.linkedin.com/in/abantika-basu-3abb851a9",
      },
      {
        id: 2,
        name: "Harsh Jha",
        avatar: "/images/member images/year 6/harshJ.jpg",
        position: "GENERAL SECRETARY",
        facebook: "https://www.facebook.com/hello.jha.wtf.hahaha.username",
        instagram: "https://instagram.com/jhatwo",
        linkedin: "https://www.linkedin.com/in/harsh-jha-0286381a6",
      },
      {
        id: 3,
        name: "Arghya",
        avatar: "/images/member images/year 6/arghya.jpg",
        position: "TREASURER",
        facebook: "https://www.facebook.com/P.a.p.a.i.0",
        instagram: "https://www.instagram.com/arghyagorai.in/",
        linkedin: "https://www.linkedin.com/in/arghya-gorai-83a7a2188/",
      },
      {
        id: 4,
        name: "Karam",
        avatar: "/images/member images/year 6/karam.jpeg",
        position: "RnD and TECH HEAD",
        facebook: "https://www.facebook.com/KaramKumarSahoo/",
        instagram: "https://www.instagram.com/a_cosmic_teen/",
        linkedin: "https://www.linkedin.com/in/karamkumarsahoo/",
      },
      {
        id: 5,
        name: "Siddharth",
        avatar: "/images/member images/year 6/siddharth.jpg",
        position: "VICE PRESIDENT",
        facebook: "https://m.facebook.com/profile.php?id=100009051800014&ref=content_filter",
        instagram: "https://www.instagram.com/_wake_up_sid._/",
        linkedin: "https://www.linkedin.com/in/siddharth-tripathi-8299861aa",
      },
      {
        id: 6,
        name: "Rishabh",
        avatar: "/images/member images/year 6/rishabh.jpg",
        position: "CONVENOR",
        facebook: "https://www.facebook.com/profile.php?id=100038906024845",
        instagram: "https://instagram.com/puru03.01",
        linkedin: "https://www.linkedin.com/in/rishabh-chauhan-b358b2201",
      },
      {
        id: 7,
        name: "Pratik",
        avatar: "/images/member images/year 6/pratik.jpg",
        position: "SPONSORSHIP HEAD",
        facebook: "https://www.facebook.com/frezcot",
        instagram: "https://instagram.com/burnn_it_downn/",
        linkedin: "https://www.linkedin.com/in/pratik-bhudari-7159831a9",
      },
      {
        id: 8,
        name: "Sayandip",
        avatar: "/images/member images/year 6/sayandip.jpeg",
        position: "ANKSHALA HEAD",
        facebook: "https://www.facebook.com/sayandip.acharjee.16",
        instagram: "https://www.instagram.com/acharjeesayandip/",
        linkedin: "https://in.linkedin.com/in/sayandip-acharjee-bb9721192",
      },
      {
        id: 9,
        name: "Swastik",
        avatar: "/images/member images/male.png",
        position: "GRAPHICS HEAD",
        facebook: "https://www.facebook.com/swastik.das.944",
        linkedin: "https://www.linkedin.com/in/swastik-das-aa9a66210",
      },
      {
        id: 10,
        name: "Kriti",
        avatar: "/images/member images/year 6/kriti.jpg",
        position: "PR HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100007515439364",
        instagram: "https://www.instagram.com/pramanikkriti27/",
        linkedin: "https://www.linkedin.com/in/kriti-pramanik-4a3ab31ab/",
      },
      {
        id: 11,
        name: "Shreya",
        avatar: "/images/member images/year 6/shreya.jpeg",
        position: "CREATIVE HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100040498443637",
        instagram: "https://www.instagram.com/shreyarai127/",
        linkedin: "https://www.linkedin.com/in/shreya-rai-8249571a9/",
      },
      {
        id: 12,
        name: "Anurag",
        avatar: "/images/member images/year 6/anurag.jpg",
        position: "LOGISTIC HEAD",
        facebook: "https://m.facebook.com/akr440",
        instagram: "https://www.instagram.com/itsanuragkr/",
        linkedin: "https://www.linkedin.com/in/anurag-kumar-699866210",
      },
      {
        id: 13,
        name: "Abhishek",
        avatar: "/images/member images/year 6/abhishek.jpeg",
        position: "EVENT HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100010224999683",
        instagram: "https://www.instagram.com/abhiking54/",
        linkedin: "https://www.linkedin.com/in/abhishek-rout-3b01ab1b5",
      },
      {
        id: 14,
        name: "Harsh Sodhani",
        avatar: "/images/member images/year 6/harshS.jpeg",
        position: "WORKSHOP HEAD",
        facebook: "https://www.facebook.com/harsh.sodhani.31",
        instagram: "https://www.instagram.com/harshsodhani/",
        linkedin: "https://www.linkedin.com/in/harsh-sodhani-338b74121/",
      },
    ]
  },
  alumni_2018_22: {
    categoryName: "Alumni 2018-22",
    members: [
      {
        id: 1,
        name: "Anto",
        avatar: "/images/member images/year 7/anto.jpeg",
        position: "PRESIDENT",
        facebook: "https://www.facebook.com/p.antoprathiksavio",
        linkedin: "https://www.linkedin.com/in/anto-prathik-savio-a29158154",
      },
      {
        id: 2,
        name: "Snehit",
        avatar: "/images/member images/year 7/snehit.jpeg",
        position: "VICE PRESIDENT",
        linkedin: "https://www.linkedin.com/in/snehit-mishra-64b391165/",
      },
      {
        id: 3,
        name: "Sharbashis",
        avatar: "/images/member images/year 7/sharbashis.jpg",
        position: "GENERAL SECRETORY",
        facebook: "https://www.facebook.com/sharbashis09/",
        instagram: "https://www.instagram.com/dundermufflin_09/",
        linkedin: " https://www.linkedin.com/in/sharbashisdas/",
      },
      {
        id: 4,
        name: "Ankan",
        avatar: "/images/member images/year 7/ankan.jpeg",
        position: "TREASURER",
        facebook: "https://www.facebook.com/ankan.chakraborty.02/",
        instagram: "https://www.instagram.com/a_n_k_a_n_02/",
        linkedin: "https://www.linkedin.com/in/ankanchakraborty02/",
      },
      {
        id: 5,
        name: "Ankita",
        avatar: "/images/member images/year 7/ankita.jpeg",
        position: "CONVENOR",
        facebook: "https://www.facebook.com/ankita.bhattacharya.161214 ",
        instagram: "https://instagram.com/bhattacharya_anki?utm_medium=copy_link",
      },
      {
        id: 6,
        name: "Shraddha",
        avatar: "/images/member images/year 7/shraddha.jpeg",
        position: "PR HEAD",
      },
      {
        id: 7,
        name: "Piyush",
        avatar: "/images/member images/year 7/piyush.jpeg",
        position: "SPONSORSHIP HEAD",
        facebook: "https://www.facebook.com/piyushkumar.dwivedi.336",
        instagram: "https://www.instagram.com/piyush.__.dwivedi/",
      },
      {
        id: 8,
        name: "Sayantan",
        avatar: "/images/member images/year 7/sayantan.jpg",
        position: "TECHNICAL HEAD",
        facebook: "https://www.facebook.com/raj.maity.311",
        instagram: "https://www.instagram.com/raj_maity_047/",
        linkedin: "https://www.linkedin.com/in/sayantan-maity-047",
      },
      {
        id: 9,
        name: "Shubhankar",
        avatar: "/images/member images/year 7/shubhankar.jpeg",
        position: "GRAPHICS HEAD",
        facebook: "https://www.facebook.com/subhankar.datta.750",
        instagram: "https://instagram.com/subhankardatta973",
        linkedin: "https://www.linkedin.com/in/subhankar-datta-909120207",
      },
      {
        id: 10,
        name: "Bighnesh",
        avatar: "/images/member images/year 7/bighnesh.jpeg",
        position: "MULTIMEDIA HEAD",
        facebook: "https://www.facebook.com/bighnesh.mohanty.37",
        instagram: "https://www.instagram.com/bighnesh__mohanty/",
        linkedin: "https://www.linkedin.com/in/bighnesh-mohanty-255b04215/",
      },
      {
        id: 11,
        name: "Risabh",
        avatar: "/images/member images/year 7/risabh.jpeg",
        position: "CREATIVE HEAD",
        facebook: "https://www.facebook.com/risabh.udgata",
        instagram: "https://instagram.com/risabh_udgata",
      },
      {
        id: 12,
        name: "Avirup",
        avatar: "/images/member images/year 7/avirup.jpeg",
        position: "LOGISTICS HEAD",
        facebook: "https://www.facebook.com/avirup.mazumder",
        instagram: "https://www.instagram.com/the_crytogenic_psysico/",
        linkedin: "https://www.linkedin.com/in/avirup-mazumder-601000181",
        github: "https://github.com/AvirupMazumder",
      },
      {
        id: 13,
        name: "Geeta",
        avatar: "/images/member images/year 7/geeta.jpeg",
        position: "LOGISTICS HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100061623151194",
        linkedin: "https://www.linkedin.com/in/gottapu-geeta-deepika-00a3461aa",
      },
      {
        id: 14,
        name: "Rabin",
        avatar: "/images/member images/year 7/rabin.jpeg",
        position: "RnD HEAD",
        facebook: "https://www.facebook.com/profile.php?id=100033457952581",
        instagram: "https://instagram.com/warrior_2093?utm_medium=copy_link",
        linkedin: "https://www.linkedin.com/in/rabin-mondal-67127b1a3",
      },
      {
        id: 15,
        name: "Harshit",
        avatar: "/images/member images/male.png",
        position: "WORKSHOP HEAD",
        facebook: "https://www.facebook.com/harshit.shrinet.1",
        instagram: "https://instagram.com/harshit_shrinet",
      },
      {
        id: 16,
        name: "Sweta",
        avatar: "/images/member images/female.png",
        position: "WORKSHOP HEAD",
      },
      {
        id: 17,
        name: "Ashwini",
        avatar: "/images/member images/year 7/ashwini.jpg",
        position: "EVENT HEAD",
      },
    ]
  },
};
